// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChatMe():Promise<Record<string, any>>;

export function GetConversations():Promise<Array<any>>;

export function GetCurrentSummoner():Promise<Record<string, any>>;

export function GetFriends():Promise<Array<any>>;

export function GetLobby():Promise<Record<string, any>>;

export function GetMatchHistory():Promise<Record<string, any>>;

export function GetRegionInfo():Promise<Record<string, any>>;

export function GetSummonerProfile():Promise<Record<string, any>>;

export function IsLCUConnected():Promise<boolean>;

export function PositionWindow():Promise<string>;

export function StartMonitoring():Promise<string>;

export function StopMonitoring():Promise<string>;
