// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChatMe() {
  return window['go']['main']['App']['GetChatMe']();
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetCurrentSummoner() {
  return window['go']['main']['App']['GetCurrentSummoner']();
}

export function GetFriends() {
  return window['go']['main']['App']['GetFriends']();
}

export function GetLobby() {
  return window['go']['main']['App']['GetLobby']();
}

export function GetMatchHistory() {
  return window['go']['main']['App']['GetMatchHistory']();
}

export function GetSummonerProfile() {
  return window['go']['main']['App']['GetSummonerProfile']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsLCUConnected() {
  return window['go']['main']['App']['IsLCUConnected']();
}

export function PositionWindow() {
  return window['go']['main']['App']['PositionWindow']();
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}
